# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718167327bd05a23eb8a5f0d85d205759aeea03f228bf858a3ceb5361a50e3d6a11a696069482b77d5645bbd975f41087a1cb099a094d2ae28d031a9a7900f57

test:
  secret_key_base: eb76ce462fbfc4463d40e2f3393c0207b3b65b6622685d3cfccae8352224697d15d77fd87418279298550418b1566d7e239f2f3ff39fb9fa0ad91e18f3735125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
